name: Build Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build application
      run: |
        pyinstaller --onefile lxpaint.py
      working-directory: ${{ github.workspace }}

    - name: Upload Linux binary
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: lxpaint-linux
        path: dist/lxpaint

    - name: Upload Windows binary
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: lxpaint-windows
        path: dist/lxpaint.exe

    - name: Upload macOS binary
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: lxpaint-macos
        path: dist/lxpaint
